name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run linting
      run: |
        pip install flake8
        flake8 . --max-line-length=120

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    - name: Run notebooks (EDA and Feature Engineering)
      run: |
        jupyter nbconvert --to notebook --execute notebook/EDA_preprocessing_train.ipynb
        jupyter nbconvert --to notebook --execute notebook/feature_engineering_train.ipynb

    - name: Commit notebook results (if any)
      run: |
        git add notebook/*.ipynb
        git commit -m "Update notebooks with execution results" || echo "No changes to commit"
        git push

    - name: Deploy to production (Optional)
      run: |
        # Add any production deployment steps if needed
        echo "Deploying to production..."
